import type { Dictionary } from "./types";

export const en: Dictionary = {
  skip: "Skip to content",
  menuOpen: "Menu",
  menuClose: "Close",
  navAria: "Primary",
  langAria: "Language",
  hero: {
    kicker: "Technical Lead · AI-Native Engineering",
    heading: "I lead software from product decisions to production.",
    tagline:
      "Technical Lead with 7+ years of experience across full-stack products, cloud infrastructure and integrations. I combine engineering leadership, product ownership and AI-native development workflows to turn complex requirements into production systems.",
    primaryCta: "View selected work",
    secondaryCta: "Let's talk",
    cvCta: "Download CV",
  },
  about: {
    kicker: "About",
    heading: "Engineering with a product lens.",
    body: [
      "I like taking loosely defined problems and turning them into maintainable systems: thinking through the architecture, making the technical calls, and carrying it all the way to production.",
      "I prefer full stack work: close to the product, the architecture, and the code that connects them. I enjoy leading technical direction while staying close to implementation and the systems we run.",
      "I orchestrate AI agents across exploration, implementation, refactoring, testing and documentation, while retaining ownership of context, architecture, validation and production quality.",
    ],
    principles: [
      {
        title: "Product thinking",
        text: "Turning ambiguous requirements into buildable systems.",
      },
      {
        title: "Engineering direction",
        text: "Architecture, priorities and technical decisions.",
      },
      {
        title: "AI orchestration",
        text: "Accelerating delivery with controlled agent workflows.",
      },
    ],
  },
  experience: {
    kicker: "Experience",
    heading: "From product delivery to technical ownership.",
    intro: "At net2phone since April 2019, remote. Promoted to Technical Lead in April 2025.",
    company: "net2phone",
    dates: "April 2019 — present",
    mode: "Remote",
    summary:
      "Technical ownership of uCRM across architecture, integrations, cloud infrastructure, delivery and team direction.",
    currentTag: "Current",
    path: [
      {
        stage: "01",
        title: "Software Developer",
        period: "April 2019 — April 2025",
        current: false,
        bullets: [
          "Implemented features end to end from requirements, with a focus on testing and documentation.",
          "Flagged gaps between spec and product and coordinated clarifications with the onboarding team instead of assuming.",
          "Built the technical knowledge of uCRM that now underpins my role as Technical Lead.",
        ],
      },
      {
        stage: "02",
        title: "Technical Lead",
        period: "April 2025 — present",
        current: true,
        bullets: [
          "I lead a team of two — one developer and one QA — and set the technical direction for uCRM.",
          "I coordinate priorities, delivery, and stakeholder conversations without stepping away from architecture and implementation.",
          "Still hands-on across full stack architecture, uContact integrations, and cloud infrastructure.",
        ],
      },
    ],
  },
  stack: {
    kicker: "Stack",
    heading: "Technologies I use to ship production software.",
    intro: "Grouped by how I use it — not a wall of logos. The core stack sits higher.",
    groups: [
      {
        title: "Core",
        items: [
          { name: "JavaScript", emphasis: "primary" },
          { name: "TypeScript", emphasis: "primary" },
          { name: "Node.js", emphasis: "primary" },
          { name: "Vue", emphasis: "primary" },
        ],
      },
      {
        title: "Backend & Data",
        items: [
          { name: "Express", emphasis: "secondary" },
          { name: "REST APIs", emphasis: "secondary" },
          { name: "MongoDB", emphasis: "secondary" },
          { name: "MySQL", emphasis: "secondary" },
        ],
      },
      {
        title: "Cloud & Delivery",
        items: [
          { name: "Google Cloud", emphasis: "primary" },
          { name: "Cloud Run", emphasis: "primary" },
          { name: "Cloud Functions", emphasis: "primary" },
          { name: "Firebase", emphasis: "primary" },
          { name: "Docker", emphasis: "primary" },
          { name: "GitHub Actions", emphasis: "primary" },
        ],
      },
      {
        title: "Infrastructure",
        items: [
          { name: "Kubernetes", emphasis: "secondary" },
          { name: "Terraform", emphasis: "secondary" },
          { name: "AWS", emphasis: "secondary" },
        ],
      },
      {
        title: "Architecture",
        items: [
          { name: "Microservices", emphasis: "secondary" },
          { name: "Event-driven architecture", emphasis: "secondary" },
        ],
      },
      {
        title: "Additional experience",
        items: [
          { name: "React", emphasis: "secondary" },
          { name: "Next.js", emphasis: "secondary" },
          { name: "Supabase", emphasis: "secondary" },
          { name: "WordPress", emphasis: "secondary" },
          { name: "Playwright", emphasis: "secondary" },
          { name: "PostgreSQL", emphasis: "secondary" },
        ],
      },
    ],
  },
  projects: {
    kicker: "Work",
    heading: "Selected work.",
    intro:
      "Each case shows a different capability: product ownership, DevOps and infrastructure, or professional client work.",
    repoLabel: "View repository",
    tradeoffsLabel: "Trade-offs",
    items: [
      {
        id: "ucrm",
        tier: 1,
        name: "uCRM",
        company: "net2phone",
        kind: "Professional product",
        summary:
          "CRM embedded in uContact for customer-interaction workflows across contact-center teams in Latin America.",
        role: "I lead its technical direction end to end: full stack architecture, product evolution, integrations, the plugin platform, and cloud infrastructure — still hands-on from design to operation.",
        responsibilities: [
          "Full stack architecture",
          "Product evolution",
          "uContact integrations",
          "Plugin platform",
          "Cloud infrastructure",
          "Deployment",
          "Operations",
        ],
        technologies: [],
        image: null,
        imageAlt: null,
        href: null,
        architectureNotes: [
          "Product context: uCRM is active across 20+ companies in more than 10 countries.",
        ],
        tradeoffs: [],
      },
      {
        id: "voting-app",
        tier: 2,
        name: "Voting App DevOps 2025",
        company: "Universidad ORT Uruguay",
        kind: "Academic capstone",
        summary:
          "Deployment of a voting app across three environments — Dev, Test, and Prod — with infrastructure as code, Kubernetes, and observability.",
        role: "Capstone project for the Analista en Tecnologías de la Información degree.",
        responsibilities: [],
        technologies: [
          "Terraform",
          "GitHub Actions",
          "Docker",
          "Kubernetes",
          "AWS EKS",
          "AWS ECR",
          "AWS Lambda",
          "CloudWatch",
          "SNS",
          "PostgreSQL",
          "Redis",
        ],
        image: null,
        imageAlt: null,
        href: "https://github.com/EnzoPeli/voting-app-devops-2025",
        architectureNotes: [
          "Terraform provisions AWS EKS across three environments — dev, test, and prod — split by workspace and namespace, running vote, result, worker, seed-data, Redis, and PostgreSQL as separate services.",
          "CI/CD pipelines (develop → Dev, test → Test, main → Prod) automate static analysis, builds, image publishing, and deploy; CloudWatch feeds Lambda and SNS for error and CPU alerting.",
        ],
        tradeoffs: [
          "NGINX Ingress was dropped in favor of independent LoadBalancer services, since Vote and Result were designed to run at `/`; PostgreSQL uses emptyDir instead of PVC, so data resets when the pod restarts.",
        ],
      },
      {
        id: "vaccichek",
        tier: 3,
        name: "VacciCheck",
        company: "Vipermed",
        kind: "Client work",
        summary:
          "Clinical decision-support app that recommends vaccines from patient characteristics, comorbidities, and risk factors, using a rules-based recommendation engine.",
        role: null,
        responsibilities: [],
        technologies: ["JavaScript", "HTML", "CSS", "Supabase"],
        image: "/projects/vaccichek.png",
        imageAlt: "VacciCheck screen: profession selection and vaccine recommendation flow",
        href: null,
        architectureNotes: [],
        tradeoffs: [],
      },
      {
        id: "shingrix",
        tier: 3,
        name: "Shingrix — Costa Rica",
        company: "GSK",
        kind: "Client work",
        summary:
          "Public education site on shingles and vaccination for Shingrix in Costa Rica. Educational content, epidemiological data visualization, and vaccination guidance, across four pages from approved brand designs.",
        role: null,
        responsibilities: [],
        technologies: ["HTML", "CSS", "JavaScript", "Playwright"],
        image: "/projects/shingrix.png",
        imageAlt: "Shingrix Costa Rica public site, education on herpes zoster",
        href: null,
        architectureNotes: [],
        tradeoffs: [],
      },
      {
        id: "abrilar",
        tier: 3,
        name: "Librería Médica Abrilar",
        company: "Vipermed",
        kind: "Client work",
        summary:
          "Private medical content platform built with WordPress and Elementor Pro — dynamic navigation, custom components, embedded resources, and user-interaction analytics.",
        role: null,
        responsibilities: [],
        technologies: [
          "WordPress",
          "Elementor Pro",
          "PHP",
          "JavaScript",
          "ACF",
          "Google Analytics",
          "Google Tag Manager",
        ],
        image: "/projects/abrilar.png",
        imageAlt: "Librería Médica Abrilar login screen",
        href: null,
        architectureNotes: [],
        tradeoffs: [],
      },
    ],
  },
  education: {
    kicker: "Education",
    heading: "Education",
    status: "Completed July 2025",
    program: "Analista en Tecnologías de la Información",
    institution: "Universidad ORT Uruguay — Montevideo",
    thesisLabel: "Capstone",
    thesisName: "Voting App DevOps 2025",
    languagesKicker: "Languages",
    languagesHeading: "Languages",
    languages: [
      { name: "Spanish", level: "Native", note: null },
      {
        name: "English",
        level: "Professional written communication and technical collaboration",
        note: null,
      },
    ],
  },
  contact: {
    kicker: "Contact",
    heading: "Let's talk about what's next.",
    intro:
      "Open to international opportunities in Technical Leadership and Engineering Management, especially in product teams working across full-stack systems, cloud platforms and AI-native delivery.",
    emailLabel: "Email",
    linkedinLabel: "LinkedIn",
    githubLabel: "GitHub",
    cvCta: "Download CV",
  },
};
