import type { Dictionary } from "./types";

export const es: Dictionary = {
  skip: "Saltar al contenido",
  menuOpen: "Menú",
  menuClose: "Cerrar",
  navAria: "Principal",
  langAria: "Idioma",
  hero: {
    kicker: "Technical Lead · Ingeniería AI-Native",
    heading: "Lidero software desde las decisiones de producto hasta producción.",
    tagline:
      "Technical Lead con más de 7 años de experiencia en productos full stack, infraestructura cloud e integraciones. Combino liderazgo de ingeniería, ownership de producto y flujos de desarrollo AI-native para convertir requerimientos complejos en sistemas confiables en producción.",
    primaryCta: "Ver trabajo seleccionado",
    secondaryCta: "Hablemos",
    cvCta: "Descargar CV",
  },
  about: {
    kicker: "Sobre mí",
    heading: "Ingeniería con mirada de producto.",
    body: [
      "Me gusta tomar problemas poco definidos y traducirlos en sistemas mantenibles: pensar la arquitectura, tomar las decisiones técnicas y llevar todo hasta producción.",
      "Prefiero el desarrollo full stack: cerca del producto, de la arquitectura y del código que los conecta. Disfruto liderar la dirección técnica sin alejarme de la implementación y de los sistemas que operamos.",
      "Orquesto agentes de IA en exploración, implementación, refactorización, testing y documentación, manteniendo el ownership del contexto, la arquitectura, la validación y la calidad en producción.",
    ],
    principles: [
      {
        title: "Mirada de producto",
        text: "Traducir requerimientos ambiguos en sistemas construibles.",
      },
      {
        title: "Dirección de ingeniería",
        text: "Arquitectura, prioridades y decisiones técnicas.",
      },
      {
        title: "Orquestación de IA",
        text: "Acelerar la entrega con flujos de agentes bajo control.",
      },
    ],
  },
  experience: {
    kicker: "Experiencia",
    heading: "De la entrega de producto a la propiedad técnica.",
    intro: "En net2phone desde abril de 2019, en remoto. Promovido a Technical Lead en abril de 2025.",
    company: "net2phone",
    dates: "Abril 2019 — presente",
    mode: "Remoto",
    summary:
      "Responsable técnico de uCRM en arquitectura, integraciones, infraestructura cloud, delivery y dirección de equipo.",
    currentTag: "Actual",
    path: [
      {
        stage: "01",
        title: "Software Developer",
        period: "Abril 2019 — abril 2025",
        current: false,
        bullets: [
          "Implementé funcionalidades de punta a punta a partir de requerimientos, con foco en testing y documentación.",
          "Señalé huecos entre el spec y el producto y coordiné aclaraciones con el equipo de onboarding en vez de asumir.",
          "Construí el conocimiento técnico de uCRM que hoy sostiene mi rol como Technical Lead.",
        ],
      },
      {
        stage: "02",
        title: "Technical Lead",
        period: "Abril 2025 — presente",
        current: true,
        bullets: [
          "Lidero un equipo de dos personas — un developer y un QA — y defino la dirección técnica de uCRM.",
          "Coordino prioridades, entregas y conversaciones con stakeholders sin dejar la arquitectura ni la implementación.",
          "Sigo hands-on en arquitectura full stack, integraciones con uContact e infraestructura cloud.",
        ],
      },
    ],
  },
  stack: {
    kicker: "Stack",
    heading: "Tecnologías con las que llevo software a producción.",
    intro: "Por cómo lo uso, no como una pared de logos. Lo principal pesa más.",
    groups: [
      {
        title: "Core",
        items: [
          { name: "JavaScript", emphasis: "primary" },
          { name: "TypeScript", emphasis: "primary" },
          { name: "Node.js", emphasis: "primary" },
          { name: "Vue", emphasis: "primary" },
        ],
      },
      {
        title: "Backend & Data",
        items: [
          { name: "Express", emphasis: "secondary" },
          { name: "REST APIs", emphasis: "secondary" },
          { name: "MongoDB", emphasis: "secondary" },
          { name: "MySQL", emphasis: "secondary" },
        ],
      },
      {
        title: "Cloud & Delivery",
        items: [
          { name: "Google Cloud", emphasis: "primary" },
          { name: "Cloud Run", emphasis: "primary" },
          { name: "Cloud Functions", emphasis: "primary" },
          { name: "Firebase", emphasis: "primary" },
          { name: "Docker", emphasis: "primary" },
          { name: "GitHub Actions", emphasis: "primary" },
        ],
      },
      {
        title: "Infrastructure",
        items: [
          { name: "Kubernetes", emphasis: "secondary" },
          { name: "Terraform", emphasis: "secondary" },
          { name: "AWS", emphasis: "secondary" },
        ],
      },
      {
        title: "Architecture",
        items: [
          { name: "Microservices", emphasis: "secondary" },
          { name: "Event-driven architecture", emphasis: "secondary" },
        ],
      },
      {
        title: "Additional experience",
        items: [
          { name: "React", emphasis: "secondary" },
          { name: "Next.js", emphasis: "secondary" },
          { name: "Supabase", emphasis: "secondary" },
          { name: "WordPress", emphasis: "secondary" },
          { name: "Playwright", emphasis: "secondary" },
          { name: "PostgreSQL", emphasis: "secondary" },
        ],
      },
    ],
  },
  projects: {
    kicker: "Proyectos",
    heading: "Trabajo seleccionado.",
    intro:
      "Cada caso muestra una capacidad distinta: ownership de producto, DevOps e infraestructura, o trabajo profesional para clientes.",
    repoLabel: "Ver repositorio",
    tradeoffsLabel: "Decisiones",
    items: [
      {
        id: "ucrm",
        tier: 1,
        name: "uCRM",
        company: "net2phone",
        kind: "Producto profesional",
        summary:
          "CRM embebido en uContact para gestionar interacciones con clientes y flujos de negocio de equipos de contact center en toda Latinoamérica.",
        role: "Lidero su dirección técnica de punta a punta: arquitectura full stack, evolución de producto, integraciones, plataforma de plugins e infraestructura cloud — sigo hands-on desde el diseño hasta la operación.",
        responsibilities: [
          "Arquitectura full stack",
          "Evolución del producto",
          "Integraciones con uContact",
          "Plataforma de plugins",
          "Infraestructura cloud",
          "Despliegue",
          "Operación",
        ],
        technologies: [],
        image: null,
        imageAlt: null,
        href: null,
        architectureNotes: [
          "Contexto del producto: uCRM está activo en más de 20 empresas de más de 10 países.",
        ],
        tradeoffs: [],
      },
      {
        id: "voting-app",
        tier: 2,
        name: "Voting App DevOps 2025",
        company: "Universidad ORT Uruguay",
        kind: "Proyecto académico",
        summary:
          "Despliegue de una app de votación en tres ambientes — Dev, Test y Prod — con infraestructura como código, Kubernetes y observabilidad.",
        role: "Proyecto final de la carrera Analista en Tecnologías de la Información.",
        responsibilities: [],
        technologies: [
          "Terraform",
          "GitHub Actions",
          "Docker",
          "Kubernetes",
          "AWS EKS",
          "AWS ECR",
          "AWS Lambda",
          "CloudWatch",
          "SNS",
          "PostgreSQL",
          "Redis",
        ],
        image: null,
        imageAlt: null,
        href: "https://github.com/EnzoPeli/voting-app-devops-2025",
        architectureNotes: [
          "Terraform aprovisiona AWS EKS en tres ambientes — dev, test y prod — separados por workspace y namespace, con vote, result, worker, seed-data, Redis y PostgreSQL como servicios independientes.",
          "Los pipelines de CI/CD (develop → Dev, test → Test, main → Prod) automatizan análisis estático, builds, publicación de imágenes y despliegue; CloudWatch alimenta Lambda y SNS para alertas de errores y CPU.",
        ],
        tradeoffs: [
          "Se descartó NGINX Ingress a favor de servicios LoadBalancer independientes, porque Vote y Result estaban pensadas para correr en `/`; PostgreSQL usa emptyDir en vez de PVC, así que los datos se reinician con el pod.",
        ],
      },
      {
        id: "vaccichek",
        tier: 3,
        name: "VacciCheck",
        company: "Vipermed",
        kind: "Proyecto para cliente",
        summary:
          "Aplicación de soporte a la decisión clínica que recomienda vacunas según características del paciente, comorbilidades y factores de riesgo, con un motor de recomendaciones basado en reglas.",
        role: null,
        responsibilities: [],
        technologies: ["JavaScript", "HTML", "CSS", "Supabase"],
        image: "/projects/vaccichek.png",
        imageAlt: "Pantalla de VacciCheck: selección de profesión y flujo de recomendación de vacunas",
        href: null,
        architectureNotes: [],
        tradeoffs: [],
      },
      {
        id: "shingrix",
        tier: 3,
        name: "Shingrix — Costa Rica",
        company: "GSK",
        kind: "Proyecto para cliente",
        summary:
          "Sitio público de educación y concientización sobre herpes zóster y vacunación para Shingrix en Costa Rica. Contenido educativo, visualización de datos epidemiológicos y orientación sobre vacunación, en cuatro páginas a partir de diseños de marca aprobados.",
        role: null,
        responsibilities: [],
        technologies: ["HTML", "CSS", "JavaScript", "Playwright"],
        image: "/projects/shingrix.png",
        imageAlt: "Sitio público de Shingrix Costa Rica, educación sobre herpes zóster",
        href: null,
        architectureNotes: [],
        tradeoffs: [],
      },
      {
        id: "abrilar",
        tier: 3,
        name: "Librería Médica Abrilar",
        company: "Vipermed",
        kind: "Proyecto para cliente",
        summary:
          "Plataforma privada de contenido médico desarrollada con WordPress y Elementor Pro, con navegación dinámica, componentes personalizados, recursos embebidos y analítica de interacción de usuarios.",
        role: null,
        responsibilities: [],
        technologies: [
          "WordPress",
          "Elementor Pro",
          "PHP",
          "JavaScript",
          "ACF",
          "Google Analytics",
          "Google Tag Manager",
        ],
        image: "/projects/abrilar.png",
        imageAlt: "Pantalla de acceso de Librería Médica Abrilar",
        href: null,
        architectureNotes: [],
        tradeoffs: [],
      },
    ],
  },
  education: {
    kicker: "Educación",
    heading: "Educación",
    status: "Finalizada en julio de 2025",
    program: "Analista en Tecnologías de la Información",
    institution: "Universidad ORT Uruguay — Montevideo",
    thesisLabel: "Proyecto final",
    thesisName: "Voting App DevOps 2025",
    languagesKicker: "Idiomas",
    languagesHeading: "Idiomas",
    languages: [
      { name: "Español", level: "Nativo", note: null },
      {
        name: "Inglés",
        level: "Comunicación escrita profesional y colaboración técnica",
        note: null,
      },
    ],
  },
  contact: {
    kicker: "Contacto",
    heading: "Hablemos de lo que sigue.",
    intro:
      "Abierto a oportunidades internacionales de Technical Leadership y Engineering Management, sobre todo en equipos de producto que trabajan con sistemas full stack, plataformas cloud y delivery AI-native.",
    emailLabel: "Email",
    linkedinLabel: "LinkedIn",
    githubLabel: "GitHub",
    cvCta: "Descargar CV",
  },
};
